# Generated by Django 6.0.7 on 2026-07-13 14:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=24, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("account", "Account"),
                            ("staff", "Staff"),
                        ],
                        default="guest",
                        max_length=12,
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("airport_pickup", "Airport pickup"),
                            ("airport_dropoff", "Airport drop-off"),
                            ("point_to_point", "Point to point"),
                        ],
                        max_length=24,
                    ),
                ),
                ("pickup_address", models.CharField(blank=True, max_length=300)),
                ("destination_address", models.CharField(blank=True, max_length=300)),
                ("pickup_locality", models.CharField(blank=True, max_length=120)),
                ("destination_locality", models.CharField(blank=True, max_length=120)),
                ("pickup_at", models.DateTimeField()),
                ("scheduled_arrival_at", models.DateTimeField(blank=True, null=True)),
                ("flight_number", models.CharField(blank=True, max_length=32)),
                ("airline", models.CharField(blank=True, max_length=120)),
                ("origin_city_country", models.CharField(blank=True, max_length=160)),
                ("terminal", models.CharField(blank=True, max_length=80)),
                ("meeting_information", models.CharField(blank=True, max_length=500)),
                (
                    "passenger_count",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("adult_count", models.PositiveSmallIntegerField(default=1)),
                ("child_count", models.PositiveSmallIntegerField(default=0)),
                ("luggage_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "oversized_luggage_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("child_seat_quantity", models.PositiveSmallIntegerField(default=0)),
                ("accessibility_request", models.BooleanField(default=False)),
                ("accessibility_details", models.CharField(blank=True, max_length=500)),
                ("additional_requirements", models.TextField(blank=True)),
                ("passenger_same_as_booker", models.BooleanField(default=True)),
                ("booker_first_name", models.CharField(max_length=150)),
                ("booker_last_name", models.CharField(max_length=150)),
                ("booker_email", models.EmailField(max_length=254)),
                ("booker_phone", models.CharField(max_length=32)),
                ("booker_whatsapp", models.CharField(blank=True, max_length=32)),
                ("passenger_first_name", models.CharField(max_length=150)),
                ("passenger_last_name", models.CharField(max_length=150)),
                ("passenger_phone", models.CharField(blank=True, max_length=32)),
                ("passenger_whatsapp", models.CharField(blank=True, max_length=32)),
                ("passenger_locale", models.CharField(default="fr", max_length=10)),
                ("locale", models.CharField(default="fr", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_payment", "Pending payment"),
                            ("confirmed", "Confirmed"),
                            ("driver_assignment_pending", "Driver assignment pending"),
                            ("driver_assigned", "Driver assigned"),
                            ("passenger_contacted", "Passenger contacted"),
                            ("driver_en_route", "Driver en route"),
                            ("driver_arrived", "Driver arrived"),
                            ("passenger_picked_up", "Passenger picked up"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No show"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("online_full", "Online in full"),
                            ("pay_later", "Pay later"),
                            ("deposit", "Deposit"),
                        ],
                        default="online_full",
                        max_length=16,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter ISO currency code."
                            )
                        ],
                    ),
                ),
                ("cancellation_deadline", models.DateTimeField(blank=True, null=True)),
                ("cancellation_outcome", models.CharField(blank=True, max_length=32)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=300)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("privacy_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="locations.airport",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="pricing.quote",
                    ),
                ),
                (
                    "service_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="locations.servicearea",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AddressSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("destination", "Destination")],
                        max_length=16,
                    ),
                ),
                ("formatted_address", models.CharField(max_length=300)),
                ("locality", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("provider_place_id", models.CharField(blank=True, max_length=160)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_snapshots",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("customer", "Customer visible"),
                        ],
                        max_length=16,
                    ),
                ),
                ("body", models.TextField(max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="BookingStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=32)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_payment", "Pending payment"),
                            ("confirmed", "Confirmed"),
                            ("driver_assignment_pending", "Driver assignment pending"),
                            ("driver_assigned", "Driver assigned"),
                            ("passenger_contacted", "Passenger contacted"),
                            ("driver_en_route", "Driver en route"),
                            ("driver_arrived", "Driver arrived"),
                            ("passenger_picked_up", "Passenger picked up"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No show"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CancellationPolicySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("text", models.TextField()),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_policy_snapshot",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("booker", "Booker"), ("passenger", "Passenger")],
                        max_length=16,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("whatsapp", models.CharField(blank=True, max_length=32)),
                ("preferred_locale", models.CharField(default="fr", max_length=10)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_snapshots",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuestAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("manage", "Manage booking")],
                        default="manage",
                        max_length=16,
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_tokens",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=80)),
                ("key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField(default=201)),
                ("response_payload", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idempotency_records",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculation_version", models.CharField(max_length=32)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter ISO currency code."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_snapshot",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=180)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("unit_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="bookings.pricesnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "pickup_at"], name="bookings_bo_status_27ae41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer", "status", "pickup_at"],
                name="bookings_bo_custome_a8acdf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booker_email", "created_at"],
                name="bookings_bo_booker__ac4525_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["airport", "pickup_at"], name="bookings_bo_airport_2f2f65_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("passenger_count__gte", 1)),
                name="bookings_passenger_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                name="bookings_currency_iso",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="bookings_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="addresssnapshot",
            constraint=models.UniqueConstraint(
                fields=("booking", "kind"), name="bookings_address_kind_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactsnapshot",
            constraint=models.UniqueConstraint(
                fields=("booking", "kind"), name="bookings_contact_kind_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="guestaccesstoken",
            index=models.Index(
                fields=["booking", "purpose", "revoked_at"],
                name="bookings_gu_booking_d54286_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("scope", "key"), name="bookings_idempotency_scope_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="priceline",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "code"), name="bookings_price_line_code_unique"
            ),
        ),
    ]
