import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import { EmptyNotice, PageHero } from "@/components/marketing";
import { getLocationsAndCoverage } from "@/lib/locations-pricing";
import { getDrivers, type DriverSearch } from "@/lib/marketplace";
import { publicMetadata } from "@/lib/seo";

export const metadata: Metadata = publicMetadata("Chauffeurs indépendants pour transferts aéroport", "Recherchez des chauffeurs professionnels vérifiés par aéroport, destination et besoins de voyage.", "/chauffeurs");

export default async function DriversPage({ searchParams }: { searchParams: Promise<DriverSearch> }) {
  const filters = await searchParams;
  const [page, locations] = await Promise.all([getDrivers(filters), getLocationsAndCoverage()]);
  return <main><PageHero eyebrow="Annuaire AirProche" title="Trouvez un chauffeur indépendant pour votre transfert aéroport" description="Comparez les profils, puis contactez directement le chauffeur qui correspond à votre trajet." />
    <section className="site-container py-12 sm:py-16"><form className="rounded-[2rem] bg-slate-950 p-5 text-white sm:p-7" action="/chauffeurs" role="search"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label><span className="form-label text-slate-200">Aéroport</span><select name="airport" defaultValue={filters.airport ?? ""} className="form-input text-slate-950"><option value="">Tous les aéroports</option>{locations.airports.map((airport) => <option key={airport.public_id} value={airport.slug}>{airport.name}</option>)}</select></label><label><span className="form-label text-slate-200">Destination ou chauffeur</span><input name="q" defaultValue={filters.q} className="form-input text-slate-950" placeholder="Paris, hôtel, nom…" /></label><label><span className="form-label text-slate-200">Sens</span><select name="direction" defaultValue={filters.direction ?? ""} className="form-input text-slate-950"><option value="">Les deux sens</option><option value="airport_to_destination">Depuis l’aéroport</option><option value="destination_to_airport">Vers l’aéroport</option></select></label><label><span className="form-label text-slate-200">Passagers</span><input type="number" min="1" max="30" name="passengers" defaultValue={filters.passengers} className="form-input text-slate-950" /></label></div><details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-blue-200">Plus de filtres</summary><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><select aria-label="Langue" name="language" defaultValue={filters.language ?? ""} className="form-input text-slate-950"><option value="">Toutes les langues</option><option value="fr">Français</option><option value="en">Anglais</option><option value="de">Allemand</option></select><select aria-label="Catégorie de véhicule" name="vehicle_category" defaultValue={filters.vehicle_category ?? ""} className="form-input text-slate-950"><option value="">Tous les véhicules</option><option value="sedan">Berline</option><option value="van">Van</option><option value="premium">Premium</option><option value="accessible">Accessible</option></select><label className="flex items-center gap-2"><input type="checkbox" name="accessible" value="true" defaultChecked={filters.accessible === "true"} />Accessible en fauteuil</label><label className="flex items-center gap-2"><input type="checkbox" name="child_seat" value="true" defaultChecked={filters.child_seat === "true"} />Siège enfant</label></div></details><div className="mt-5 flex flex-wrap gap-3"><button className="button bg-blue-600 text-white hover:bg-blue-500">Rechercher</button><Link className="button border border-white/30 text-white" href="/chauffeurs">Effacer les filtres</Link></div></form>
      <div className="mt-10 flex flex-wrap items-center justify-between gap-4"><p className="text-sm font-bold text-slate-700">{page.count} chauffeur{page.count > 1 ? "s" : ""} publié{page.count > 1 ? "s" : ""}</p><form><input type="hidden" name="airport" value={filters.airport ?? ""} /><select aria-label="Trier les chauffeurs" name="sort" defaultValue={filters.sort ?? ""} className="form-input" onChange={undefined}><option value="">Pertinence</option><option value="response_time">Temps de réponse</option><option value="experience">Expérience</option><option value="newest">Profils récents</option></select><button className="sr-only">Trier</button></form></div>
      {page.results.length ? <div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{page.results.map((driver) => <article className="group overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-sm" key={driver.public_id}><div className="relative aspect-[16/9] bg-gradient-to-br from-blue-100 to-slate-200">{driver.profile_photo_url ? <Image src={driver.profile_photo_url} alt={`Portrait professionnel de ${driver.display_name}`} fill className="object-cover" sizes="(min-width:1280px) 30vw, (min-width:768px) 45vw, 100vw" /> : <div className="grid h-full place-items-center text-5xl font-black text-blue-800">{driver.display_name.slice(0, 1)}</div>}<span className="absolute left-4 top-4 rounded-full bg-white px-3 py-1 text-xs font-black text-blue-800 shadow">Profil vérifié</span></div><div className="p-6"><h2 className="text-2xl font-black text-slate-950">{driver.display_name}</h2><p className="mt-1 text-sm text-slate-500">{driver.business_name || "Chauffeur indépendant"} · jusqu’à {driver.max_passengers} passagers</p><p className="mt-4 line-clamp-3 text-sm leading-6 text-slate-600">{driver.bio || "Profil professionnel vérifié sur AirProche."}</p><p className="mt-4 text-sm font-semibold text-slate-700">{driver.airports.map((airport) => airport.iata_code).join(" · ")}</p><p className="mt-2 text-xs text-slate-500">Disponibilité à confirmer auprès du chauffeur.</p><Link className="button button-primary mt-6 w-full" href={`/chauffeurs/${driver.slug}`}>Voir et contacter</Link></div></article>)}</div> : <div className="mt-8"><EmptyNotice title="Aucun chauffeur ne correspond à ces critères"><p>Élargissez les filtres ou recherchez un autre aéroport. Aucune disponibilité n’est fabriquée.</p></EmptyNotice></div>}
    </section></main>;
}
