# Generated by Django 6.0.7 on 2026-07-13 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('verify_email', 'Email verification'), ('reset_password', 'Password reset'), ('booking_created', 'Booking created'), ('booking_status', 'Booking status'), ('contact_received', 'Contact received')], max_length=32)),
                ('template_key', models.CharField(max_length=64)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('locale', models.CharField(default='fr', max_length=10)),
                ('context', models.JSONField(default=dict)),
                ('related_type', models.CharField(blank=True, max_length=32)),
                ('related_public_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('retryable', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_1d75ae_idx'), models.Index(fields=['related_type', 'related_public_id'], name='notificatio_related_a017b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('topic', models.CharField(choices=[('booking', 'Booking'), ('quote', 'Quote'), ('payment', 'Payment'), ('accessibility', 'Accessibility'), ('other', 'Other')], max_length=24)),
                ('message', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', max_length=24)),
                ('staff_notes', models.TextField(blank=True, max_length=4000)),
                ('source_fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('request_hash', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_5ffbd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('request_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('provider_response', models.CharField(blank=True, max_length=200)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.emailnotification')),
            ],
            options={
                'ordering': ('-attempt_number',),
                'constraints': [models.UniqueConstraint(fields=('notification', 'attempt_number'), name='notifications_attempt_number_unique')],
            },
        ),
    ]
