# Generated by Django 6.0.7 on 2026-07-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailnotification",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="error_category",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="provider_identifier",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="safe_error_summary",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("verify_email", "Email verification"),
                    ("reset_password", "Password reset"),
                    ("booking_created", "Booking created"),
                    ("booking_status", "Booking status"),
                    ("contact_received", "Contact received"),
                    ("inquiry_customer_ack", "Inquiry customer acknowledgement"),
                    ("inquiry_driver_new", "New inquiry for driver"),
                    ("inquiry_status", "Inquiry status update"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="emailnotification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("retrying", "Retrying"),
                    ("permanent_failure", "Permanent failure"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
    ]
