# Generated by Django 6.0.7 on 2026-07-13 13:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("airport_pickup", "Airport pickup"),
                            ("airport_dropoff", "Airport drop-off"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter ISO currency code."
                            )
                        ],
                    ),
                ),
                ("passenger_capacity", models.PositiveSmallIntegerField(default=4)),
                ("luggage_capacity", models.PositiveSmallIntegerField(default=4)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tariffs",
                        to="locations.airport",
                    ),
                ),
                (
                    "service_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tariffs",
                        to="locations.servicearea",
                    ),
                ),
            ],
            options={
                "ordering": ("-priority", "-valid_from"),
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("airport_pickup", "Airport pickup"),
                            ("airport_dropoff", "Airport drop-off"),
                        ],
                        max_length=24,
                    ),
                ),
                ("airport_name", models.CharField(max_length=180)),
                ("airport_iata_code", models.CharField(max_length=3)),
                ("service_area_name", models.CharField(max_length=160)),
                ("pickup_at", models.DateTimeField()),
                ("passenger_count", models.PositiveSmallIntegerField()),
                ("luggage_count", models.PositiveSmallIntegerField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter ISO currency code."
                            )
                        ],
                    ),
                ),
                (
                    "calculation_version",
                    models.CharField(default="fixed-zone-v1", max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("valid", "Valid"), ("expired", "Expired")],
                        default="valid",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="locations.airport",
                    ),
                ),
                (
                    "service_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="locations.servicearea",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="pricing.tariff",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TariffOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=140)),
                (
                    "pricing_method",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("per_unit", "Per unit")],
                        default="per_unit",
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a three-letter ISO currency code."
                            )
                        ],
                    ),
                ),
                ("maximum_quantity", models.PositiveSmallIntegerField(default=1)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tariff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="pricing.tariff",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "code"),
            },
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=180)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("unit_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="pricing.quote",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("quote", "code"), name="pricing_quote_line_code_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)),
                        name="pricing_quote_line_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_amount__gte", 0)),
                        name="pricing_quote_line_unit_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_amount__gte", 0)),
                        name="pricing_quote_line_total_nonnegative",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tariff",
            index=models.Index(
                fields=[
                    "airport",
                    "service_area",
                    "trip_type",
                    "is_active",
                    "valid_from",
                ],
                name="pricing_tar_airport_bf9479_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariff",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="pricing_tariff_valid_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariff",
            constraint=models.CheckConstraint(
                condition=models.Q(("passenger_capacity__gte", 1)),
                name="pricing_tariff_passenger_capacity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariff",
            constraint=models.CheckConstraint(
                condition=models.Q(("luggage_capacity__gte", 0)),
                name="pricing_tariff_luggage_capacity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariff",
            constraint=models.UniqueConstraint(
                fields=("airport", "service_area", "trip_type", "valid_from"),
                name="pricing_tariff_route_start_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["public_id", "expires_at"],
                name="pricing_quo_public__4e12d9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(("passenger_count__gte", 1)),
                name="pricing_quote_passengers_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(("luggage_count__gte", 0)),
                name="pricing_quote_luggage_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="pricing_quote_total_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="tariffoption",
            index=models.Index(
                fields=["code", "is_active", "valid_from"],
                name="pricing_tar_code_5ba78a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariffoption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="pricing_option_valid_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariffoption",
            constraint=models.CheckConstraint(
                condition=models.Q(("maximum_quantity__gte", 1)),
                name="pricing_option_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariffoption",
            constraint=models.UniqueConstraint(
                fields=("code", "tariff", "valid_from"),
                name="pricing_option_code_tariff_start_unique",
            ),
        ),
    ]
