# Generated by Django 6.0.7 on 2026-07-13 17:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=32)),
                (
                    "max_passengers",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_areas",
                    models.ManyToManyField(
                        blank=True, related_name="drivers", to="locations.servicearea"
                    ),
                ),
            ],
            options={
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("registration", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=120)),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("luggage_capacity", models.PositiveSmallIntegerField(default=4)),
                ("accessibility_capable", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("label", "registration"),
                "indexes": [
                    models.Index(
                        fields=["active", "label"], name="operations__active_6c6a77_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DriverAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("unassigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "released_to_customer_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("override_reason", models.CharField(blank=True, max_length=500)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="driver_assignments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="operations.driver",
                    ),
                ),
                (
                    "unassigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_assignments_removed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="operations.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ("-assigned_at",),
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("object_id", models.CharField(max_length=80)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="operations__action_4be119_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="operations__content_007d4e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["active", "last_name"], name="operations__active_acec36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driverassignment",
            index=models.Index(
                fields=["driver", "unassigned_at"],
                name="operations__driver__d91440_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driverassignment",
            index=models.Index(
                fields=["vehicle", "unassigned_at"],
                name="operations__vehicle_8bf4cf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="driverassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("unassigned_at__isnull", True)),
                fields=("booking",),
                name="operations_one_active_assignment_per_booking",
            ),
        ),
    ]
