# Generated by Django 6.0.7 on 2026-07-14 12:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceDriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=180)),
                ('business_name', models.CharField(blank=True, max_length=180)),
                ('business_identifier', models.CharField(blank=True, max_length=80)),
                ('vtc_card_number', models.CharField(blank=True, max_length=80)),
                ('insurance_provider', models.CharField(blank=True, max_length=180)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('phone', models.CharField(max_length=32)),
                ('max_passengers', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('is_published', models.BooleanField(default=False)),
                ('accepts_quote_requests', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airports', models.ManyToManyField(blank=True, related_name='marketplace_drivers', to='locations.airport')),
                ('service_areas', models.ManyToManyField(blank=True, related_name='marketplace_drivers', to='locations.servicearea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='DriverInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=180)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=32)),
                ('destination', models.CharField(max_length=300)),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
                ('passenger_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.airport')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='operations.marketplacedriverprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='marketplacedriverprofile',
            index=models.Index(fields=['is_published', 'verification_status'], name='operations__is_publ_653d00_idx'),
        ),
        migrations.AddIndex(
            model_name='driverinquiry',
            index=models.Index(fields=['driver', 'status', 'created_at'], name='operations__driver__7f240a_idx'),
        ),
    ]
