# Generated by Django 6.0.7 on 2026-07-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_marketplacedriverprofile_driverinquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacedriverprofile',
            name='accepted_payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
