# Generated by Django 6.0.7 on 2026-07-15 07:30

import apps.operations.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("operations", "0003_marketplacedriverprofile_accepted_payment_methods"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverVerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("identity", "Justificatif d’identité"),
                            ("vtc_card", "Carte professionnelle VTC"),
                            ("insurance", "Attestation d’assurance"),
                            ("business", "Immatriculation professionnelle"),
                            ("vehicle", "Carte grise"),
                            ("other", "Autre"),
                        ],
                        max_length=24,
                    ),
                ),
                ("file", models.FileField(upload_to=apps.operations.models.private_document_path)),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending_scan", "Analyse en attente"),
                            ("pending_review", "Examen en attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Refusé"),
                            ("expired", "Expiré"),
                        ],
                        default="pending_scan",
                        max_length=24,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DriverVerificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("safe_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="InquiryConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("privacy_policy_version", models.CharField(max_length=80)),
                ("consent_text_version", models.CharField(max_length=80)),
                ("consent_granted", models.BooleanField()),
                ("source", models.CharField(default="driver_profile", max_length=80)),
                ("allowed_contact_channels", models.JSONField(default=list)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InquiryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("customer_visible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InquiryStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=16)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("notified", "Notified"),
                            ("viewed", "Viewed"),
                            ("contacted", "Contacted"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                            ("spam", "Spam"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("customer_visible_note", models.CharField(blank=True, max_length=500)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("changed_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="MarketplaceVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sedan", "Berline"),
                            ("van", "Van"),
                            ("premium", "Premium"),
                            ("accessible", "Accessible"),
                        ],
                        default="sedan",
                        max_length=24,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=60)),
                (
                    "passenger_capacity",
                    models.PositiveSmallIntegerField(
                        default=4, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("luggage_capacity", models.PositiveSmallIntegerField(default=2)),
                ("registration", models.CharField(blank=True, max_length=32)),
                (
                    "public_photo",
                    models.FileField(blank=True, upload_to="marketplace/vehicle-photos/%Y/%m/"),
                ),
                ("air_conditioning", models.BooleanField(default=True)),
                ("child_seat", models.BooleanField(default=False)),
                ("wheelchair_accessible", models.BooleanField(default=False)),
                ("pets_allowed", models.BooleanField(default=False)),
                ("non_smoking", models.BooleanField(default=True)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="anonymized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="customer_whatsapp",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="direction",
            field=models.CharField(
                choices=[
                    ("airport_to_destination", "Airport to destination"),
                    ("destination_to_airport", "Destination to airport"),
                ],
                default="airport_to_destination",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="luggage_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[("email", "Email"), ("phone", "Phone"), ("whatsapp", "WhatsApp")],
                default="email",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="reference",
            field=models.CharField(
                default=apps.operations.models.inquiry_reference,
                editable=False,
                max_length=24,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="request_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="source_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="spam_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driverinquiry",
            name="whatsapp_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="availability_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="cancellation_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="certifications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="directions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="indicative_price_currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="indicative_price_from",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="insurance_policy_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="insurance_valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="maximum_radius_km",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="minimum_notice_hours",
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[("email", "Email"), ("phone", "Phone"), ("whatsapp", "WhatsApp")],
                default="email",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="pricing_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="professional_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="professional_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="profile_photo",
            field=models.FileField(blank=True, upload_to="marketplace/profile-photos/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="show_phone_publicly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="show_whatsapp_publicly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="status_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="typical_response_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="vtc_issuing_authority",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="vtc_valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="whatsapp_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="marketplacedriverprofile",
            name="years_experience",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="driverinquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("notified", "Notified"),
                    ("viewed", "Viewed"),
                    ("contacted", "Contacted"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                    ("spam", "Spam"),
                ],
                default="new",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="marketplacedriverprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under review"),
                    ("changes_requested", "Changes requested"),
                    ("verified", "Verified"),
                    ("suspended", "Suspended"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="driverinquiry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("driver", "idempotency_key"),
                name="operations_driver_inquiry_idempotency_unique",
            ),
        ),
        migrations.AddField(
            model_name="driververificationdocument",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_documents",
                to="operations.marketplacedriverprofile",
            ),
        ),
        migrations.AddField(
            model_name="driververificationdocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="driververificationevent",
            name="actor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="driververificationevent",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_events",
                to="operations.marketplacedriverprofile",
            ),
        ),
        migrations.AddField(
            model_name="inquiryconsent",
            name="inquiry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent",
                to="operations.driverinquiry",
            ),
        ),
        migrations.AddField(
            model_name="inquirynote",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="inquirynote",
            name="inquiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="operations.driverinquiry",
            ),
        ),
        migrations.AddField(
            model_name="inquirystatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inquirystatushistory",
            name="inquiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="operations.driverinquiry",
            ),
        ),
        migrations.AddField(
            model_name="marketplacevehicle",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace_vehicle",
                to="operations.marketplacedriverprofile",
            ),
        ),
    ]
