# Generated by Django 6.0.7 on 2026-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('operations', '0004_driververificationdocument_driververificationevent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='driverinquiry',
            name='operations_driver_inquiry_idempotency_unique',
        ),
        migrations.AlterField(
            model_name='driverinquiry',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='driverinquiry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('driver', 'idempotency_key'), name='operations_driver_inquiry_idempotency_unique'),
        ),
    ]
