# Generated by Django 6.0.7 on 2026-07-13 12:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_name",
                    models.CharField(default="Transfert Privé", max_length=160),
                ),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                (
                    "tagline",
                    models.CharField(
                        default="Votre transfert aéroport, organisé avec soin.",
                        max_length=200,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("whatsapp_phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("support_hours", models.CharField(blank=True, max_length=160)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country_code", models.CharField(default="FR", max_length=2)),
                ("booking_enabled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "business settings",
                "verbose_name_plural": "business settings",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=260)),
                ("answer", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("display_order", "question"),
            },
        ),
        migrations.CreateModel(
            name="ServiceContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("summary", models.CharField(max_length=260)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("plane", "Airport transfer"),
                            ("luggage", "Luggage assistance"),
                            ("home", "Home transfer"),
                            ("hotel", "Hotel transfer"),
                            ("users", "Relatives and groups"),
                            ("route", "Long-distance transfer"),
                        ],
                        default="route",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("display_order", "title"),
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_name", models.CharField(max_length=120)),
                ("author_context", models.CharField(blank=True, max_length=160)),
                ("quote", models.TextField(max_length=1000)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        help_text="Internal source or consent reference. Never exposed publicly.",
                        max_length=300,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("display_order", "-verified_at"),
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("privacy", "Privacy policy"),
                            ("terms", "Terms and conditions"),
                            ("cancellation", "Cancellation policy"),
                            ("legal_notice", "Legal notice"),
                            ("cookies", "Cookie policy"),
                        ],
                        max_length=24,
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("effective_at", models.DateTimeField()),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("kind", "-effective_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "version"),
                        name="content_legal_kind_version_unique",
                    )
                ],
            },
        ),
    ]
