# Generated by Django 6.0.7 on 2026-07-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="maximum_booking_days",
            field=models.PositiveSmallIntegerField(default=365),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="minimum_lead_hours",
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="quote_valid_minutes",
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
