"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import { ProfileShareActions } from "./profile-share-actions";
import { DriverInbox } from "./driver-inbox";

type Location = { public_id: string; name: string };
type Profile = { slug: string; display_name: string; business_name: string; business_identifier: string; professional_status: string; bio: string; professional_email: string; phone: string; whatsapp_phone: string; years_experience: number; vtc_card_number: string; vtc_issuing_authority: string; insurance_provider: string; max_passengers: number; languages: string[]; directions: string[]; accepted_payment_methods: string[]; airport_ids: string[]; service_area_ids: string[]; indicative_price_from: string | null; pricing_note: string; typical_response_minutes: number | null; availability_note: string; verification_status: string; is_published: boolean; completion_percent: number; vehicle?: { make: string; model: string; category: string; passenger_capacity: number; luggage_capacity: number; child_seat: boolean; wheelchair_accessible: boolean; air_conditioning: boolean; non_smoking: boolean } };

const profileLabels: Record<string, string> = { draft: "Brouillon", submitted: "Soumis", under_review: "En cours d’examen", changes_requested: "Modifications demandées", verified: "Vérifié", suspended: "Suspendu", rejected: "Refusé", archived: "Archivé" };

export function DriverDashboard() {
  const [profile, setProfile] = useState<Profile | null | undefined>(undefined);
  const [airports, setAirports] = useState<Location[]>([]);
  const [areas, setAreas] = useState<Location[]>([]);
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);

  useEffect(() => { Promise.all([
    fetch("/api/v1/marketplace/me/profile/", { credentials: "same-origin", cache: "no-store" }).then((response) => response.ok ? response.json() : null),
    fetch("/api/v1/marketplace/me/options/", { credentials: "same-origin", cache: "no-store" }).then((response) => response.ok ? response.json() : { airports: [], service_areas: [] }),
  ]).then(([nextProfile, options]) => { setProfile(nextProfile); setAirports(options.airports); setAreas(options.service_areas); }).catch(() => { setMessage("L’espace chauffeur est momentanément indisponible."); setProfile(null); }); }, []);

  async function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (saving) return; setSaving(true); setMessage("");
    const form = new FormData(event.currentTarget); const data = Object.fromEntries(form);
    try {
      const csrf = await fetch("/api/v1/auth/csrf/", { credentials: "same-origin" }).then((response) => response.json());
      const payload = { ...data, years_experience: Number(data.years_experience), max_passengers: Number(data.max_passengers), typical_response_minutes: data.typical_response_minutes ? Number(data.typical_response_minutes) : null, indicative_price_from: data.indicative_price_from || null, languages: form.getAll("languages"), directions: form.getAll("directions"), accepted_payment_methods: form.getAll("accepted_payment_methods"), airport_ids: form.getAll("airport_ids"), service_area_ids: form.getAll("service_area_ids"), vehicle: { make: data.vehicle_make, model: data.vehicle_model, category: data.vehicle_category, passenger_capacity: Number(data.vehicle_passenger_capacity), luggage_capacity: Number(data.vehicle_luggage_capacity), child_seat: form.get("vehicle_child_seat") === "on", wheelchair_accessible: form.get("vehicle_wheelchair_accessible") === "on", air_conditioning: form.get("vehicle_air_conditioning") === "on", non_smoking: form.get("vehicle_non_smoking") === "on" } };
      ["vehicle_make","vehicle_model","vehicle_category","vehicle_passenger_capacity","vehicle_luggage_capacity","vehicle_child_seat","vehicle_wheelchair_accessible","vehicle_air_conditioning","vehicle_non_smoking"].forEach((key) => delete (payload as Record<string, unknown>)[key]);
      const response = await fetch("/api/v1/marketplace/me/profile/", { method: profile ? "PATCH" : "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": csrf.csrf_token }, body: JSON.stringify(payload) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || result.detail || "Enregistrement impossible."); setProfile(result); setMessage("Profil enregistré. Toute modification sensible est réexaminée avant publication.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Enregistrement impossible."); }
    finally { setSaving(false); }
  }

  if (profile === undefined) return <section className="mt-10 border-t border-slate-200 pt-10" role="status"><div className="h-8 w-56 animate-pulse rounded bg-slate-200 motion-reduce:animate-none" /><div className="mt-5 h-52 animate-pulse rounded-2xl bg-slate-100 motion-reduce:animate-none" /><span className="sr-only">Chargement du profil chauffeur</span></section>;
  return <section className="mt-10 border-t border-slate-200 pt-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Espace chauffeur</p><h2 className="mt-2 text-2xl font-black">Mon profil professionnel</h2></div>{profile?.is_published ? <Link className="button button-primary" href={`/chauffeurs/${profile.slug}`} target="_blank">Ouvrir le profil public</Link> : null}</div>
    {profile ? <div className="mt-6 grid gap-4 sm:grid-cols-3"><State label="Statut" value={profileLabels[profile.verification_status] ?? "À vérifier"} /><State label="Publication" value={profile.is_published ? "Publié" : "Non publié"} /><State label="Complétude" value={`${profile.completion_percent}%`} /></div> : <p className="mt-5 rounded-xl bg-blue-50 p-4 text-sm leading-6 text-blue-950">Créez votre fiche. Elle restera invisible jusqu’à la vérification et la publication par AirProche.</p>}
    {profile?.slug ? <div className="mt-6 rounded-2xl bg-slate-950 p-6 text-white"><h3 className="text-xl font-black">Partager mon profil</h3><p className="mt-2 text-sm text-slate-300">Prévisualisez le lien canonique et utilisez le QR code sur vos supports professionnels.</p><div className="mt-5"><ProfileShareActions name={profile.display_name} path={`/chauffeurs/${profile.slug}`} showQr /></div></div> : null}
    <form onSubmit={save} className="mt-7 grid gap-8"><Fieldset legend="Identité publique"><div className="grid gap-4 sm:grid-cols-2"><Input required name="display_name" label="Nom professionnel affiché" value={profile?.display_name} /><Input name="business_name" label="Nom commercial" value={profile?.business_name} /><Input name="business_identifier" label="SIREN/SIRET ou identifiant professionnel" value={profile?.business_identifier} /><Input name="professional_status" label="Statut professionnel" value={profile?.professional_status} /><Input required type="email" name="professional_email" label="E-mail professionnel" value={profile?.professional_email} /><Input required type="tel" name="phone" label="Téléphone professionnel" value={profile?.phone} /></div><label className="block"><span className="form-label">Présentation</span><textarea required minLength={80} name="bio" className="form-input min-h-32" defaultValue={profile?.bio} /></label></Fieldset>
      <Fieldset legend="Informations professionnelles"><div className="grid gap-4 sm:grid-cols-2"><Input required name="vtc_card_number" label="Numéro de carte professionnelle VTC" value={profile?.vtc_card_number} /><Input name="vtc_issuing_authority" label="Autorité émettrice" value={profile?.vtc_issuing_authority} /><Input required name="insurance_provider" label="Assureur professionnel" value={profile?.insurance_provider} /><Input required type="number" min="0" max="80" name="years_experience" label="Années d’expérience" value={profile?.years_experience ?? 0} /></div></Fieldset>
      <Fieldset legend="Aéroports et zones"><p className="text-sm text-slate-600">Au moins un aéroport actif est obligatoire avant publication.</p><Checkboxes name="airport_ids" values={airports} selected={profile?.airport_ids ?? []} /><div className="mt-4"><Checkboxes name="service_area_ids" values={areas} selected={profile?.service_area_ids ?? []} /></div><div className="mt-4 flex flex-wrap gap-4"><Check name="directions" value="airport_to_destination" label="Aéroport vers destination" checked={profile?.directions.includes("airport_to_destination")} /><Check name="directions" value="destination_to_airport" label="Destination vers aéroport" checked={profile?.directions.includes("destination_to_airport")} /></div></Fieldset>
      <Fieldset legend="Langues et contact"><div className="flex flex-wrap gap-4">{[["fr","Français"],["en","Anglais"],["de","Allemand"],["es","Espagnol"]].map(([value,label]) => <Check key={value} name="languages" value={value} label={label} checked={profile?.languages.includes(value)} />)}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Input name="whatsapp_phone" label="WhatsApp professionnel" value={profile?.whatsapp_phone} /><Input required type="number" min="1" max="30" name="max_passengers" label="Capacité maximale" value={profile?.max_passengers ?? 4} /></div></Fieldset>
      <Fieldset legend="Véhicule"><div className="grid gap-4 sm:grid-cols-2"><Input required name="vehicle_make" label="Marque" value={profile?.vehicle?.make} /><Input required name="vehicle_model" label="Modèle" value={profile?.vehicle?.model} /><label><span className="form-label">Catégorie</span><select name="vehicle_category" className="form-input" defaultValue={profile?.vehicle?.category ?? "sedan"}><option value="sedan">Berline</option><option value="van">Van</option><option value="premium">Premium</option><option value="accessible">Accessible</option></select></label><Input required type="number" min="1" name="vehicle_passenger_capacity" label="Places passagers" value={profile?.vehicle?.passenger_capacity ?? 4} /><Input required type="number" min="0" name="vehicle_luggage_capacity" label="Capacité bagages" value={profile?.vehicle?.luggage_capacity ?? 2} /></div><div className="mt-4 flex flex-wrap gap-4"><Check name="vehicle_child_seat" label="Siège enfant" checked={profile?.vehicle?.child_seat} /><Check name="vehicle_wheelchair_accessible" label="Accessible en fauteuil" checked={profile?.vehicle?.wheelchair_accessible} /><Check name="vehicle_air_conditioning" label="Climatisation" checked={profile?.vehicle?.air_conditioning ?? true} /><Check name="vehicle_non_smoking" label="Non-fumeur" checked={profile?.vehicle?.non_smoking ?? true} /></div></Fieldset>
      <Fieldset legend="Informations commerciales"><div className="grid gap-4 sm:grid-cols-2"><Input type="number" min="0" step="0.01" name="indicative_price_from" label="Tarif indicatif à partir de (€)" value={profile?.indicative_price_from ?? ""} /><Input type="number" min="1" name="typical_response_minutes" label="Temps de réponse habituel (minutes)" value={profile?.typical_response_minutes ?? ""} /></div><Input name="pricing_note" label="Précisions tarifaires" value={profile?.pricing_note} /><Input name="availability_note" label="Disponibilité indicative" value={profile?.availability_note} /><div className="mt-4 flex flex-wrap gap-4">{[["cash","Espèces"],["card_terminal","Carte sur terminal"],["bank_transfer","Virement"],["private_payment_link","Lien privé"]].map(([value,label]) => <Check key={value} name="accepted_payment_methods" value={value} label={label} checked={profile?.accepted_payment_methods.includes(value)} />)}</div><p className="mt-4 text-xs text-slate-500">Les tarifs restent indicatifs et doivent être confirmés directement avec le client. AirProche n’encaisse pas le transport.</p></Fieldset>
      <button className="button button-primary" type="submit" disabled={saving}>{saving ? "Enregistrement…" : profile ? "Enregistrer les modifications" : "Créer mon profil"}</button>{message ? <p role="status" className="text-sm font-semibold text-slate-700">{message}</p> : null}
    </form>
    {profile ? <DriverInbox /> : null}
  </section>;
}

function Fieldset({ legend, children }: { legend: string; children: React.ReactNode }) { return <fieldset className="rounded-2xl border border-slate-200 p-5 sm:p-7"><legend className="px-2 text-lg font-black">{legend}</legend><div className="grid gap-4">{children}</div></fieldset>; }
function Input({ label, value, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; value?: string | number | null }) { return <label><span className="form-label">{label}{props.required ? " *" : ""}</span><input {...props} className="form-input" defaultValue={value ?? ""} /></label>; }
function Check({ label, checked, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input {...props} type="checkbox" defaultChecked={checked} className="size-4" />{label}</label>; }
function Checkboxes({ name, values, selected }: { name: string; values: Location[]; selected: string[] }) { return <div className="grid max-h-52 gap-2 overflow-auto rounded-xl bg-slate-50 p-4 sm:grid-cols-2">{values.map((item) => <Check key={item.public_id} name={name} value={item.public_id} label={item.name} checked={selected.includes(item.public_id)} />)}</div>; }
function State({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-100 p-4"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 font-black">{value}</p></div>; }
