# Generated by Django 6.0.7 on 2026-07-13 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_alter_user_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("verify_email", "Verify email"),
                            ("reset_password", "Reset password"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "consumed_at"],
                        name="accounts_ac_user_id_20035c_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_ac_expires_c6ddfb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms and conditions"),
                            ("privacy", "Privacy acknowledgement"),
                        ],
                        max_length=24,
                    ),
                ),
                ("document_version", models.CharField(max_length=32)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type", "granted_at"],
                        name="accounts_co_user_id_b14df3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "consent_type", "document_version"),
                        name="accounts_user_consent_version_unique",
                    )
                ],
            },
        ),
    ]
