import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

import { InquiryForm } from "@/features/marketplace/inquiry-form";
import { ProfileShareActions } from "@/features/marketplace/profile-share-actions";
import { getDriver } from "@/lib/marketplace";
import { getPublicContent } from "@/lib/public-content";
import { absoluteUrl } from "@/lib/seo";

const languageLabels: Record<string, string> = { fr: "Français", en: "Anglais", de: "Allemand", es: "Espagnol", it: "Italien", pt: "Portugais", ar: "Arabe" };
const paymentLabels: Record<string, string> = { cash: "Espèces", card_terminal: "Carte sur terminal", bank_transfer: "Virement bancaire", private_payment_link: "Lien de paiement privé" };

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const driver = await getDriver((await params).id);
  if (!driver) return { title: "Chauffeur introuvable", robots: { index: false, follow: false } };
  const airports = driver.airports.map((airport) => airport.iata_code).join(", ");
  const title = `${driver.display_name}, chauffeur transfert aéroport ${airports}`;
  const description = `Profil vérifié sur AirProche. Contactez ${driver.display_name} pour un transfert depuis ou vers ${airports}. Tarif et disponibilité à confirmer directement.`;
  return { title, description, alternates: { canonical: `/chauffeurs/${driver.slug}` }, openGraph: { title, description, url: `/chauffeurs/${driver.slug}`, type: "profile", images: driver.profile_photo_url ? [{ url: driver.profile_photo_url }] : undefined } };
}

export default async function DriverPage({ params }: { params: Promise<{ id: string }> }) {
  const driver = await getDriver((await params).id); if (!driver) notFound();
  const content = await getPublicContent();
  const privacyVersion = content.legal_documents.find((document) => document.kind === "privacy")?.version;
  const path = `/chauffeurs/${driver.slug}`;
  const structuredData = { "@context": "https://schema.org", "@type": "ProfessionalService", name: driver.display_name, url: absoluteUrl(path), description: driver.bio, areaServed: driver.service_areas.map((area) => area.name), image: driver.profile_photo_url || undefined, provider: { "@type": "Person", name: driver.display_name } };
  return <main className="bg-[#f7faff]"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replaceAll("<", "\\u003c") }} />
    <section className="border-b border-slate-200 bg-white"><div className="site-container py-4"><Link className="text-sm font-bold text-blue-700" href="/chauffeurs">← Découvrir d’autres chauffeurs</Link></div></section>
    <section className="site-container py-10 sm:py-14"><div className="grid items-center gap-8 lg:grid-cols-[0.72fr_1.28fr]"><div className="relative mx-auto aspect-square w-full max-w-sm overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-blue-100 to-slate-200 shadow-xl">{driver.profile_photo_url ? <Image src={driver.profile_photo_url} alt={`Portrait professionnel de ${driver.display_name}`} fill priority className="object-cover" sizes="384px" /> : <div className="grid h-full place-items-center text-8xl font-black text-blue-800">{driver.display_name.slice(0, 1)}</div>}</div><div><p className="inline-flex rounded-full bg-blue-50 px-4 py-2 text-sm font-black text-blue-800">✓ Profil professionnel vérifié sur AirProche</p><h1 className="mt-5 text-4xl font-black tracking-[-0.045em] text-slate-950 sm:text-6xl">{driver.display_name}</h1><p className="mt-3 text-lg font-semibold text-slate-600">{driver.business_name || "Chauffeur indépendant spécialisé dans les transferts aéroport"}</p><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-700">{driver.bio}</p><div className="mt-7"><ProfileShareActions name={driver.display_name} path={path} /></div></div></div></section>
    <section className="site-container grid gap-8 pb-24 lg:grid-cols-[minmax(0,0.9fr)_minmax(24rem,0.7fr)]"><div className="grid gap-8"><section className="rounded-[2rem] bg-slate-950 p-7 text-white sm:p-9"><h2 className="text-2xl font-black">Aéroports et destinations</h2><div className="mt-6 grid gap-6 sm:grid-cols-2"><div><h3 className="text-sm font-black uppercase tracking-wider text-blue-300">Aéroports desservis</h3><ul className="mt-3 grid gap-2">{driver.airports.map((airport) => <li key={airport.public_id}>{airport.name} ({airport.iata_code})</li>)}</ul></div><div><h3 className="text-sm font-black uppercase tracking-wider text-blue-300">Zones habituelles</h3><ul className="mt-3 grid gap-2">{driver.service_areas.map((area) => <li key={area.public_id}>{area.name}</li>)}</ul></div></div><p className="mt-6 text-sm text-slate-300">Sens proposés : depuis l’aéroport et/ou vers l’aéroport selon les informations du formulaire. Toute disponibilité reste à confirmer.</p></section>
      <section className="grid gap-5 sm:grid-cols-2"><Info title="Expérience" value={`${driver.years_experience} an${driver.years_experience > 1 ? "s" : ""}`} /><Info title="Langues" value={driver.languages.map((language) => languageLabels[language] ?? language).join(", ") || "À confirmer"} /><Info title="Capacité" value={`Jusqu’à ${driver.max_passengers} passagers`} /><Info title="Réponse habituelle" value={driver.typical_response_minutes ? `Environ ${driver.typical_response_minutes} minutes` : "À confirmer"} /></section>
      {driver.vehicle ? <section className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white"><div className="relative aspect-[16/7] bg-slate-100">{driver.vehicle.photo_url ? <Image src={driver.vehicle.photo_url} alt={`Véhicule ${driver.vehicle.make} ${driver.vehicle.model}`} fill className="object-cover" sizes="800px" /> : null}</div><div className="p-7"><h2 className="text-2xl font-black">Le véhicule</h2><p className="mt-2 text-lg text-slate-700">{driver.vehicle.make} {driver.vehicle.model}{driver.vehicle.year ? ` · ${driver.vehicle.year}` : ""}</p><ul className="mt-5 grid gap-2 text-sm text-slate-600 sm:grid-cols-2"><li>{driver.vehicle.passenger_capacity} passagers</li><li>{driver.vehicle.luggage_capacity} bagages</li><li>{driver.vehicle.child_seat ? "Siège enfant disponible" : "Pas de siège enfant déclaré"}</li><li>{driver.vehicle.wheelchair_accessible ? "Accessibilité fauteuil déclarée" : "Accessibilité fauteuil non déclarée"}</li><li>{driver.vehicle.air_conditioning ? "Climatisation" : "Climatisation non déclarée"}</li><li>{driver.vehicle.non_smoking ? "Véhicule non-fumeur" : "Politique tabac à confirmer"}</li></ul></div></section> : null}
      <section className="rounded-[2rem] border border-blue-200 bg-blue-50 p-7"><h2 className="text-2xl font-black text-slate-950">Tarif et paiement</h2><p className="mt-4 leading-7 text-slate-700">{driver.indicative_price_from ? `À partir de ${new Intl.NumberFormat("fr-FR", { style: "currency", currency: driver.indicative_price_currency }).format(Number(driver.indicative_price_from))}. ` : ""}{driver.pricing_note}</p><p className="mt-3 text-sm font-bold text-blue-950">Tarif indicatif communiqué par le chauffeur. Le montant final doit être confirmé directement avec lui.</p><p className="mt-3 text-sm text-slate-600">Moyens déclarés : {driver.accepted_payment_methods.map((method) => paymentLabels[method] ?? method).join(", ") || "à confirmer"}.</p></section>
      <section className="rounded-[2rem] border border-slate-200 bg-white p-7"><h2 className="text-2xl font-black">Sécurité et rôle d’AirProche</h2><p className="mt-4 leading-7 text-slate-600">AirProche vérifie le profil selon le périmètre indiqué, met les parties en relation et sécurise la transmission de la demande. Le chauffeur reste indépendant et confirme lui-même la disponibilité, le tarif, le contrat de transport et le paiement.</p><Link href="/transparence" className="mt-4 inline-block font-bold text-blue-700 underline">Comprendre le fonctionnement de la plateforme</Link></section></div>
      <aside id="contact" className="lg:sticky lg:top-24 lg:self-start">{privacyVersion && driver.accepts_quote_requests ? <InquiryForm driverId={driver.slug} driverName={driver.display_name} airports={driver.airports} privacyVersion={privacyVersion} /> : <div className="surface-card p-7"><h2 className="text-xl font-black">Demandes momentanément indisponibles</h2><p className="mt-3 text-sm leading-6 text-slate-600">Le formulaire sera disponible dès que la politique de confidentialité publiée pourra être acceptée.</p></div>}</aside></section>
    <div className="fixed inset-x-3 bottom-3 z-40 lg:hidden"><a className="button button-primary w-full shadow-xl" href="#contact">Contacter ce chauffeur</a></div>
  </main>;
}

function Info({ title, value }: { title: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs font-black uppercase tracking-wider text-blue-700">{title}</p><p className="mt-2 text-lg font-bold text-slate-950">{value}</p></div>; }
