# Generated by Django 6.0.7 on 2026-07-13 13:43

import apps.locations.models
import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "iata_code",
                    models.CharField(
                        max_length=3,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z]{3}$", "Use a three-letter IATA code."
                            )
                        ],
                    ),
                ),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("city", models.CharField(max_length=120)),
                ("country_code", models.CharField(default="FR", max_length=2)),
                ("address", models.CharField(max_length=300)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Paris", max_length=64)),
                ("terminal_guidance", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=170)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("city", "City"),
                            ("region", "Region"),
                            ("postal_zone", "Postal zone"),
                            ("custom", "Custom area"),
                        ],
                        max_length=20,
                    ),
                ),
                ("country_code", models.CharField(default="FR", max_length=2)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "postal_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.locations.models.validate_string_list],
                    ),
                ),
                ("provider_place_id", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
    ]
