# Generated by Django 6.0.7 on 2026-07-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="checkout_url",
            field=models.URLField(blank=True),
        ),
    ]
